language: go
install:
  - npm install -g kinesalite
script:
  - kinesalite --createStreamMs 5 --deleteStreamMs 5 &
  - go test
  - killall node
notifications:
  email: false
branches:
  only:
    - master
    - development
